import './global.css';
import { ReduxProvider } from '../store/provider';

export const metadata = {
  title: 'Realtime Analytics',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        style={{
          margin: 0,
          backgroundColor: '#faf8f3',
          fontFamily:
            '-apple-system, BlinkMacSystemFont, Inter, Roboto, sans-serif',
        }}
      >
        <ReduxProvider>{children}</ReduxProvider>
      </body>
    </html>
  );
}

